version: '3.1'
services:
  mysqlservice:
    image: mysql
    container_name: mysqldb
    command: --default_authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: clavedb
    networks:
      - test_network

  mysql_workbench:
    image: lscr.io/linuxserver/mysql-workbench:latest
    container_name: mysql-workbench
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    ports:
      - "3000:3000"
      - "3001:3001"
    cap_add:
      - IPC_LOCK
    restart: unless-stopped
    networks:
      - test_network
    volumes:
      - ./chinook-database:/Chinook
networks:
  test_network:
    name: test_network